# This workflow is intended to support repositories that have changed their default branch (typically, from `master` to `main`).
# It will force-push to `master` whenever `main` is updated.
# Assuming the default branch has already been renamed on GitHub; the following may be run in any local clones:
#     ```sh
#     git branch -m master main
#     git fetch origin
#     git branch -u origin/main main
#     git remote set-head origin -a
#     ```

name: Sync Branches
on:
  push: { branches: main }
  workflow_dispatch:

jobs:
  master:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - run: git push --force origin HEAD:refs/heads/master
