name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest
    steps:
    
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Reset system Homebrew installation
      if: matrix.os == 'macOS-latest'
      run: brew update-reset
