name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: brew style .
    - run: brew audit --strict Formula/*
    - run: brew install Formula/*
    - run: brew test Formula/*
